package generator

import (
	"fmt"
	"go/ast"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

// Model represents a discovered GORM model with its package metadata.
type Model struct {
	Package string // full import path
	Alias   string // package alias (last segment of path)
	Type    string // struct name
}

// RunGenerate is the main entry point.
// It scans Go packages, finds GORM models, generates a temporary file,
// executes it to produce schema, runs atlas migration diff,
// and finally cleans up generated artifacts.
func RunGenerate(path string, driver string) {
	models, err := scanModels(path)
	if err != nil {
		panic(err)
	}

	if len(models) == 0 {
		fmt.Println("no gorm models found")
		return
	}

	// Generate temporary Go file with collected models
	if err := generateFile(models, driver); err != nil {
		panic(err)
	}

	fmt.Println("models_gen.go generated successfully")

	// Execute generated file to output schema
	if err := runCommand("go", "run", "models_gen.go"); err != nil {
		return
	}

	// Run atlas migration diff based on selected driver
	if err := runAtlasDiff(driver); err != nil {
		return
	}

	// Cleanup generated file
	_ = os.Remove("models_gen.go")
}

// scanModels loads Go packages and extracts all structs
// that embed gorm.Model or equivalent.
func scanModels(path string) ([]Model, error) {
	var models []Model

	cfg := &packages.Config{
		Mode: packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedName |
			packages.NeedSyntax,
		Dir: ".",
	}

	pkgs, err := packages.Load(cfg, fmt.Sprintf("%s/...", path))
	if err != nil {
		return nil, err
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}

		alias := filepath.Base(pkg.PkgPath)

		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {

				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {

					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					// Check if struct is a GORM model
					if !hasGormModel(structType) {
						continue
					}

					models = append(models, Model{
						Package: pkg.PkgPath,
						Alias:   alias,
						Type:    typeSpec.Name.Name,
					})
				}
			}
		}
	}

	return models, nil
}

// hasGormModel checks whether a struct embeds gorm.Model
// or a custom Model type.
func hasGormModel(st *ast.StructType) bool {
	for _, field := range st.Fields.List {

		// Skip named fields (we only care about embedded ones)
		if field.Names != nil {
			continue
		}

		switch t := field.Type.(type) {

		// Case: gorm.Model
		case *ast.SelectorExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				if ident.Name == "gorm" && t.Sel.Name == "Model" {
					return true
				}
			}

		// Case: Model (custom embedding)
		case *ast.Ident:
			if t.Name == "Model" {
				return true
			}
		}
	}

	return false
}

// generateFile creates a temporary Go file that uses atlas gormschema
// to convert models into SQL schema statements.
func generateFile(models []Model, driver string) error {
	file, err := os.Create("models_gen.go")
	if err != nil {
		return err
	}
	defer file.Close()

	var builder strings.Builder

	// File header
	builder.WriteString(`// Code generated by gorm.migrateloader DO NOT EDIT.
// Version: v0.0.1

// Built By: go install
`)

	builder.WriteString("package main\n\n")

	// Collect unique imports
	builder.WriteString("import (\n")

	imports := map[string]string{}
	for _, m := range models {
		imports[m.Package] = m.Alias
	}

	for path, alias := range imports {
		builder.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, path))
	}

	builder.WriteString(`
	"fmt"
	"io"
	"os"

	"ariga.io/atlas-provider-gorm/gormschema"
`)
	builder.WriteString(")\n\n")

	// Build model slice
	builder.WriteString("var Models = []any{\n")
	for _, m := range models {
		builder.WriteString(fmt.Sprintf("\t&%s.%s{},\n", m.Alias, m.Type))
	}
	builder.WriteString("}\n")

	// Generate main function
	builder.WriteString(fmt.Sprintf(`
func main() {
	stmts, err := gormschema.New("%s").Load(Models...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %%v\n", err)
		os.Exit(1)
	}

	if _, err = io.WriteString(os.Stdout, stmts); err != nil {
		panic(err)
	}
}
`, driver))

	_, err = file.WriteString(builder.String())
	return err
}

// runAtlasDiff executes atlas migration diff using proper env.
func runAtlasDiff(driver string) error {
	env := resolveAtlasEnv(driver)
	return runCommand("atlas", "migrate", "diff", "migration", "--env", env)
}

// resolveAtlasEnv maps driver to atlas environment name.
func resolveAtlasEnv(driver string) string {
	switch driver {
	case "sqlite":
		return "gorm_sqlite"
	case "postgres":
		return "gorm_postgres"
	default:
		return "gorm_postgres"
	}
}

// runCommand is a helper to execute shell commands with inherited stdio.
func runCommand(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Dir = "."

	return cmd.Run()
}
